apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
  template:
    metadata:
      name: myapp
      labels:
        app: myjavaapp
    spec:
      containers:
        - name: myjavacontainer
          image: maha4iac/myonlinebooking:1
          ports:
            - containerPort: 8080
